stages:
  - validate
  - build
  - test
  - security
  - sast
  - dependency-check
  - docker
  - gitops

validate:
  stage: validate
  script:
    - echo "Pipeline Started"
    - echo "TaskFlow CI Working"

frontend-build:
  stage: build
  image: node:20

  before_script:
    - cd frontend
    - npm install

  script:
    - npm run build

  artifacts:
    paths:
      - frontend/dist

backend-test:
  stage: test
  image: node:20

  before_script:
    - cd backend
    - npm install

  script:
    - node --version
    - npm list --depth=0

trivy-fs-scan:
  stage: security

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  script:
    - trivy fs . --format json -o trivy-fs-report.json

  artifacts:
    paths:
      - trivy-fs-report.json
    expire_in: 1 week

  allow_failure: true

trivy-k8s-scan:
  stage: security

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  script:
    - trivy config k8s/ --format json -o trivy-k8s-report.json

  artifacts:
    paths:
      - trivy-k8s-report.json
    expire_in: 1 week

  allow_failure: true

trivy-helm-scan:
  stage: security

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  script:
    - trivy config taskflow-chart/ --format json -o trivy-helm-report.json

  artifacts:
    paths:
      - trivy-helm-report.json
    expire_in: 1 week

  allow_failure: true

semgrep-sast:
  stage: sast

  image: returntocorp/semgrep

  script:
    - semgrep --config=auto . --json --output semgrep-report.json

  artifacts:
    paths:
      - semgrep-report.json
    expire_in: 1 week

  allow_failure: true
owasp-dependency-check:
  stage: dependency-check

  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]

  script:
    - mkdir -p reports
    - |
      /usr/share/dependency-check/bin/dependency-check.sh \
      --scan . \
      --format HTML \
      --out reports || true

  artifacts:
    paths:
      - reports/

  allow_failure: true

docker-build-backend:
  stage: docker

  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  script:
    - docker build -t abhaysahu403/taskflow-backend:$CI_COMMIT_SHORT_SHA ./backend
    - docker tag abhaysahu403/taskflow-backend:$CI_COMMIT_SHORT_SHA abhaysahu403/taskflow-backend:latest
    - docker push abhaysahu403/taskflow-backend:$CI_COMMIT_SHORT_SHA
    - docker push abhaysahu403/taskflow-backend:latest

docker-build-frontend:
  stage: docker

  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  script:
    - docker build -t abhaysahu403/taskflow-frontend:$CI_COMMIT_SHORT_SHA ./frontend
    - docker tag abhaysahu403/taskflow-frontend:$CI_COMMIT_SHORT_SHA abhaysahu403/taskflow-frontend:latest
    - docker push abhaysahu403/taskflow-frontend:$CI_COMMIT_SHORT_SHA
    - docker push abhaysahu403/taskflow-frontend:latest

trivy-image-backend:
  stage: security

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  script:
    - trivy image --format json -o backend-image-report.json abhaysahu403/taskflow-backend:latest

  artifacts:
    paths:
      - backend-image-report.json
    expire_in: 1 week

  allow_failure: true


trivy-image-frontend:
  stage: security

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  script:
    - trivy image --format json -o frontend-image-report.json abhaysahu403/taskflow-frontend:latest

  artifacts:
    paths:
      - frontend-image-report.json
    expire_in: 1 week

  allow_failure: true

update-helm-values:
  stage: gitops

  image: alpine:latest

  before_script:
    - apk add --no-cache git sed

  script:
    - git config --global user.email "gitlab-ci@gitlab.com"
    - git config --global user.name "GitLab CI"

    - echo "Updating Helm Chart Image Tags..."

    - sed -i "s/tag: latest/tag: ${CI_COMMIT_SHORT_SHA}/g" taskflow-chart/values.yaml

    - cat taskflow-chart/values.yaml

    - git add taskflow-chart/values.yaml

    - |
      git commit -m "GitOps: update image tag ${CI_COMMIT_SHORT_SHA}" || echo "No changes"

    - git remote set-url origin https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/abhaysahucse/taskflow.git

    - git push origin HEAD:main

  only:
    - main