apiVersion: v1
kind: Pod
metadata:
  name: config-secret-demo
  namespace: rbac-lab

spec:
  containers:
  - name: demo
    image: nginx

    envFrom:
    - configMapRef:
        name: app-config

    - secretRef:
        name: app-secret