apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
  namespace: rbac-lab

spec:
  containers:
  - name: nginx
    image: nginx

    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"

      limits:
        cpu: "200m"
        memory: "256Mi"