apiVersion: v1
kind: Secret

metadata:
  name: taskflow-secret
  namespace: taskflow

type: Opaque

stringData:
  MYSQL_USER: taskflow_user
  MYSQL_PASSWORD: taskflow_password
  JWT_SECRET: your_super_secret_jwt_key_change_in_production