namespace: taskflow

frontend:
  image: abhaysahu403/taskflow-frontend
  tag: 0758b267
  replicas: 2

backend:
  image: abhaysahu403/taskflow-backend
  tag: 0758b267
  replicas: 2

mysql:
  image: mysql
  tag: 0758b267

redis:
  image: redis
  tag: 0758b267

storage:
  size: 2Gi

ingress:
  host: taskflow-gitops.local