namespace: taskflow

frontend:
  image: abhaysahu403/taskflow-frontend
  tag: 36493a7b
  replicas: 2

backend:
  image: abhaysahu403/taskflow-backend
  tag: 36493a7b
  replicas: 2

mysql:
  image: mysql
  tag: 36493a7b

redis:
  image: redis
  tag: 36493a7b

storage:
  size: 2Gi

ingress:
  host: taskflow-gitops.local